name: wine-latest
version: 'core22'
summary: Wine platform snap that provides latest stable WINE for snaps
description: |
 This snap creates the latest WINE stable via content sharing to be used by other snaps that are using WINE.
grade: stable
confinement: strict
base: core22
compression: lzo
architectures:
  - build-on: amd64

slots:
  wine-latest:
    interface: content
    source:
      read:
      - "."

package-repositories:
  - type: apt
    architectures: [i386,amd64]
    key-id: 0x76F1A20FF987672F
    key-server: https://dl.winehq.org/wine-builds/winehq.key
    formats: [deb]
    components: [main]
    suites: [jammy]
    url: https://dl.winehq.org/wine-builds/ubuntu


parts:
  wine:
    plugin: nil
    stage-packages:
      - winehq-stable
